apiVersion: v1
kind: Pod
metadata:
  name: prime-server

spec:
  containers:
  - image: prime-api:latest
    imagePullPolicy: Never
    name: prime-server
    ports:
    - containerPort: 5000 
      protocol: TCP
