apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-api
  template:
    metadata:
      labels:
        app: prime-api
    spec:
      containers:
      - name: prime-api
        image: prime-api:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: prime-api-service
spec:
  type: NodePort
  selector:
    app: prime-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
